# Generated by Django 4.0.5 on 2022-07-14 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
