# Generated by Django 4.0.5 on 2022-07-14 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_customer_address_customer_hphone_customer_mphone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='hphone',
            new_name='home_phone',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='mphone',
            new_name='mobile_phone',
        ),
    ]
